export {
    deviceProperties,
    deviceReadingsProperties,
    deviceRecordingsProperties,
    type Granularity,
    locationProperties,
    locationReadingsProperties,
    type PublicDevice,
    publicDeviceColumns,
    publicReadingColumns,
    readingCreateProperties,
    readingProperties,
    READINGS_SERIES_MAX_POINTS,
    readingsPageProperties,
    readingsQueryProperties,
    recordingCreateProperties,
    recordingProperties,
    sensorProperties,
} from '~/lib/schemas/sensor';
