import type {
    Equipment,
    ForceVector,
    Mechanic,
    MuscleGroup,
} from '~/lib/lifting/types';

import { db } from '../..';
import { liftingExercise, liftingExerciseAlias } from '../../schemas/lifting';
import { DatabaseSeeder } from '../../types';

interface SeedExercise {
    aliases: string[];
    defaultRestSeconds?: number;
    equipment: Equipment;
    force: ForceVector;
    mechanic: Mechanic;
    name: string;
    primaryMuscle: MuscleGroup;
    secondaryMuscles: MuscleGroup[];
    slug: string;
    tags?: string[];
}

const EXERCISES: readonly SeedExercise[] = [
    {
        aliases: ['bench', 'flat bench', 'bb bench'],
        defaultRestSeconds: 180,
        equipment: 'barbell',
        force: 'push',
        mechanic: 'compound',
        name: 'Barbell Bench Press',
        primaryMuscle: 'chest',
        secondaryMuscles: ['triceps', 'shoulders'],
        slug: 'barbell-bench-press',
        tags: ['powerlifting', 'main-lift'],
    },
    {
        aliases: ['incline bench'],
        defaultRestSeconds: 150,
        equipment: 'barbell',
        force: 'push',
        mechanic: 'compound',
        name: 'Incline Barbell Bench Press',
        primaryMuscle: 'chest',
        secondaryMuscles: ['shoulders', 'triceps'],
        slug: 'incline-barbell-bench-press',
    },
    {
        aliases: ['db bench', 'dumbbell bench'],
        defaultRestSeconds: 150,
        equipment: 'dumbbell',
        force: 'push',
        mechanic: 'compound',
        name: 'Dumbbell Bench Press',
        primaryMuscle: 'chest',
        secondaryMuscles: ['triceps', 'shoulders'],
        slug: 'dumbbell-bench-press',
    },
    {
        aliases: ['incline db bench'],
        defaultRestSeconds: 150,
        equipment: 'dumbbell',
        force: 'push',
        mechanic: 'compound',
        name: 'Incline Dumbbell Bench Press',
        primaryMuscle: 'chest',
        secondaryMuscles: ['shoulders', 'triceps'],
        slug: 'incline-dumbbell-bench-press',
    },
    {
        aliases: ['db fly'],
        defaultRestSeconds: 90,
        equipment: 'dumbbell',
        force: 'push',
        mechanic: 'isolation',
        name: 'Dumbbell Fly',
        primaryMuscle: 'chest',
        secondaryMuscles: ['shoulders'],
        slug: 'dumbbell-fly',
    },
    {
        aliases: ['cable fly', 'pec fly'],
        defaultRestSeconds: 75,
        equipment: 'cable',
        force: 'push',
        mechanic: 'isolation',
        name: 'Cable Fly',
        primaryMuscle: 'chest',
        secondaryMuscles: ['shoulders'],
        slug: 'cable-fly',
    },
    {
        aliases: ['pushup'],
        defaultRestSeconds: 60,
        equipment: 'bodyweight',
        force: 'push',
        mechanic: 'compound',
        name: 'Push-Up',
        primaryMuscle: 'chest',
        secondaryMuscles: ['triceps', 'shoulders', 'abs'],
        slug: 'push-up',
    },
    {
        aliases: ['squat', 'back squat', 'bb squat'],
        defaultRestSeconds: 210,
        equipment: 'barbell',
        force: 'squat',
        mechanic: 'compound',
        name: 'Barbell Back Squat',
        primaryMuscle: 'quads',
        secondaryMuscles: ['glutes', 'hamstrings', 'abs'],
        slug: 'barbell-back-squat',
        tags: ['powerlifting', 'main-lift'],
    },
    {
        aliases: ['front squat'],
        defaultRestSeconds: 180,
        equipment: 'barbell',
        force: 'squat',
        mechanic: 'compound',
        name: 'Barbell Front Squat',
        primaryMuscle: 'quads',
        secondaryMuscles: ['glutes', 'abs'],
        slug: 'barbell-front-squat',
    },
    {
        aliases: ['goblet'],
        defaultRestSeconds: 90,
        equipment: 'dumbbell',
        force: 'squat',
        mechanic: 'compound',
        name: 'Goblet Squat',
        primaryMuscle: 'quads',
        secondaryMuscles: ['glutes'],
        slug: 'goblet-squat',
    },
    {
        aliases: ['hack squat'],
        defaultRestSeconds: 120,
        equipment: 'machine',
        force: 'squat',
        mechanic: 'compound',
        name: 'Hack Squat',
        primaryMuscle: 'quads',
        secondaryMuscles: ['glutes'],
        slug: 'hack-squat',
    },
    {
        aliases: ['leg press'],
        defaultRestSeconds: 120,
        equipment: 'machine',
        force: 'squat',
        mechanic: 'compound',
        name: 'Leg Press',
        primaryMuscle: 'quads',
        secondaryMuscles: ['glutes', 'hamstrings'],
        slug: 'leg-press',
    },
    {
        aliases: ['leg ext'],
        defaultRestSeconds: 75,
        equipment: 'machine',
        force: 'push',
        mechanic: 'isolation',
        name: 'Leg Extension',
        primaryMuscle: 'quads',
        secondaryMuscles: [],
        slug: 'leg-extension',
    },
    {
        aliases: ['lunge', 'walking lunge'],
        defaultRestSeconds: 90,
        equipment: 'dumbbell',
        force: 'squat',
        mechanic: 'compound',
        name: 'Dumbbell Walking Lunge',
        primaryMuscle: 'quads',
        secondaryMuscles: ['glutes', 'hamstrings'],
        slug: 'dumbbell-walking-lunge',
    },
    {
        aliases: ['rdl'],
        defaultRestSeconds: 150,
        equipment: 'barbell',
        force: 'hinge',
        mechanic: 'compound',
        name: 'Romanian Deadlift',
        primaryMuscle: 'hamstrings',
        secondaryMuscles: ['glutes', 'back'],
        slug: 'romanian-deadlift',
    },
    {
        aliases: ['conventional dead', 'deadlift'],
        defaultRestSeconds: 240,
        equipment: 'barbell',
        force: 'hinge',
        mechanic: 'compound',
        name: 'Conventional Deadlift',
        primaryMuscle: 'hamstrings',
        secondaryMuscles: ['glutes', 'back', 'forearms', 'traps'],
        slug: 'conventional-deadlift',
        tags: ['powerlifting', 'main-lift'],
    },
    {
        aliases: ['sumo dead'],
        defaultRestSeconds: 240,
        equipment: 'barbell',
        force: 'hinge',
        mechanic: 'compound',
        name: 'Sumo Deadlift',
        primaryMuscle: 'glutes',
        secondaryMuscles: ['hamstrings', 'back', 'quads'],
        slug: 'sumo-deadlift',
    },
    {
        aliases: ['leg curl'],
        defaultRestSeconds: 75,
        equipment: 'machine',
        force: 'pull',
        mechanic: 'isolation',
        name: 'Seated Leg Curl',
        primaryMuscle: 'hamstrings',
        secondaryMuscles: [],
        slug: 'seated-leg-curl',
    },
    {
        aliases: ['hip thrust'],
        defaultRestSeconds: 120,
        equipment: 'barbell',
        force: 'hinge',
        mechanic: 'compound',
        name: 'Barbell Hip Thrust',
        primaryMuscle: 'glutes',
        secondaryMuscles: ['hamstrings'],
        slug: 'barbell-hip-thrust',
    },
    {
        aliases: ['calf raise', 'standing calf'],
        defaultRestSeconds: 60,
        equipment: 'machine',
        force: 'push',
        mechanic: 'isolation',
        name: 'Standing Calf Raise',
        primaryMuscle: 'calves',
        secondaryMuscles: [],
        slug: 'standing-calf-raise',
    },
    {
        aliases: ['ohp', 'overhead press', 'standing press'],
        defaultRestSeconds: 180,
        equipment: 'barbell',
        force: 'push',
        mechanic: 'compound',
        name: 'Overhead Press',
        primaryMuscle: 'shoulders',
        secondaryMuscles: ['triceps', 'traps', 'abs'],
        slug: 'overhead-press',
    },
    {
        aliases: ['db shoulder press', 'seated db press'],
        defaultRestSeconds: 120,
        equipment: 'dumbbell',
        force: 'push',
        mechanic: 'compound',
        name: 'Seated Dumbbell Shoulder Press',
        primaryMuscle: 'shoulders',
        secondaryMuscles: ['triceps'],
        slug: 'seated-dumbbell-shoulder-press',
    },
    {
        aliases: ['lat raise', 'side raise'],
        defaultRestSeconds: 60,
        equipment: 'dumbbell',
        force: 'pull',
        mechanic: 'isolation',
        name: 'Dumbbell Lateral Raise',
        primaryMuscle: 'shoulders',
        secondaryMuscles: ['traps'],
        slug: 'dumbbell-lateral-raise',
    },
    {
        aliases: ['rear delt fly', 'reverse fly'],
        defaultRestSeconds: 60,
        equipment: 'dumbbell',
        force: 'pull',
        mechanic: 'isolation',
        name: 'Rear Delt Fly',
        primaryMuscle: 'shoulders',
        secondaryMuscles: ['back'],
        slug: 'rear-delt-fly',
    },
    {
        aliases: ['face pull'],
        defaultRestSeconds: 60,
        equipment: 'cable',
        force: 'pull',
        mechanic: 'isolation',
        name: 'Face Pull',
        primaryMuscle: 'shoulders',
        secondaryMuscles: ['traps', 'back'],
        slug: 'face-pull',
    },
    {
        aliases: ['shrug', 'bb shrug'],
        defaultRestSeconds: 75,
        equipment: 'barbell',
        force: 'pull',
        mechanic: 'isolation',
        name: 'Barbell Shrug',
        primaryMuscle: 'traps',
        secondaryMuscles: ['forearms'],
        slug: 'barbell-shrug',
    },
    {
        aliases: ['pull-up', 'pullup'],
        defaultRestSeconds: 150,
        equipment: 'bodyweight',
        force: 'pull',
        mechanic: 'compound',
        name: 'Pull-Up',
        primaryMuscle: 'lats',
        secondaryMuscles: ['biceps', 'back', 'forearms'],
        slug: 'pull-up',
    },
    {
        aliases: ['chin-up', 'chinup'],
        defaultRestSeconds: 150,
        equipment: 'bodyweight',
        force: 'pull',
        mechanic: 'compound',
        name: 'Chin-Up',
        primaryMuscle: 'lats',
        secondaryMuscles: ['biceps', 'back'],
        slug: 'chin-up',
    },
    {
        aliases: ['lat pulldown', 'pulldown'],
        defaultRestSeconds: 90,
        equipment: 'cable',
        force: 'pull',
        mechanic: 'compound',
        name: 'Lat Pulldown',
        primaryMuscle: 'lats',
        secondaryMuscles: ['biceps', 'back'],
        slug: 'lat-pulldown',
    },
    {
        aliases: ['bb row', 'pendlay row'],
        defaultRestSeconds: 150,
        equipment: 'barbell',
        force: 'pull',
        mechanic: 'compound',
        name: 'Barbell Row',
        primaryMuscle: 'back',
        secondaryMuscles: ['biceps', 'lats', 'forearms'],
        slug: 'barbell-row',
    },
    {
        aliases: ['db row', 'one arm row'],
        defaultRestSeconds: 90,
        equipment: 'dumbbell',
        force: 'pull',
        mechanic: 'compound',
        name: 'Single-Arm Dumbbell Row',
        primaryMuscle: 'back',
        secondaryMuscles: ['biceps', 'lats'],
        slug: 'single-arm-dumbbell-row',
    },
    {
        aliases: ['seated cable row', 'seated row'],
        defaultRestSeconds: 90,
        equipment: 'cable',
        force: 'pull',
        mechanic: 'compound',
        name: 'Seated Cable Row',
        primaryMuscle: 'back',
        secondaryMuscles: ['biceps', 'lats'],
        slug: 'seated-cable-row',
    },
    {
        aliases: ['t-bar row', 'tbar row'],
        defaultRestSeconds: 120,
        equipment: 'machine',
        force: 'pull',
        mechanic: 'compound',
        name: 'T-Bar Row',
        primaryMuscle: 'back',
        secondaryMuscles: ['biceps', 'lats', 'traps'],
        slug: 't-bar-row',
    },
    {
        aliases: ['curl', 'bb curl'],
        defaultRestSeconds: 75,
        equipment: 'barbell',
        force: 'pull',
        mechanic: 'isolation',
        name: 'Barbell Curl',
        primaryMuscle: 'biceps',
        secondaryMuscles: ['forearms'],
        slug: 'barbell-curl',
    },
    {
        aliases: ['db curl'],
        defaultRestSeconds: 60,
        equipment: 'dumbbell',
        force: 'pull',
        mechanic: 'isolation',
        name: 'Dumbbell Curl',
        primaryMuscle: 'biceps',
        secondaryMuscles: ['forearms'],
        slug: 'dumbbell-curl',
    },
    {
        aliases: ['hammer'],
        defaultRestSeconds: 60,
        equipment: 'dumbbell',
        force: 'pull',
        mechanic: 'isolation',
        name: 'Hammer Curl',
        primaryMuscle: 'biceps',
        secondaryMuscles: ['forearms'],
        slug: 'hammer-curl',
    },
    {
        aliases: ['preacher'],
        defaultRestSeconds: 60,
        equipment: 'barbell',
        force: 'pull',
        mechanic: 'isolation',
        name: 'Preacher Curl',
        primaryMuscle: 'biceps',
        secondaryMuscles: ['forearms'],
        slug: 'preacher-curl',
    },
    {
        aliases: ['skull crusher', 'lying tricep ext'],
        defaultRestSeconds: 60,
        equipment: 'barbell',
        force: 'push',
        mechanic: 'isolation',
        name: 'Skull Crusher',
        primaryMuscle: 'triceps',
        secondaryMuscles: [],
        slug: 'skull-crusher',
    },
    {
        aliases: ['tri pushdown', 'tricep pushdown'],
        defaultRestSeconds: 60,
        equipment: 'cable',
        force: 'push',
        mechanic: 'isolation',
        name: 'Tricep Pushdown',
        primaryMuscle: 'triceps',
        secondaryMuscles: [],
        slug: 'tricep-pushdown',
    },
    {
        aliases: ['overhead tri ext'],
        defaultRestSeconds: 60,
        equipment: 'dumbbell',
        force: 'push',
        mechanic: 'isolation',
        name: 'Overhead Tricep Extension',
        primaryMuscle: 'triceps',
        secondaryMuscles: [],
        slug: 'overhead-tricep-extension',
    },
    {
        aliases: ['dip'],
        defaultRestSeconds: 120,
        equipment: 'bodyweight',
        force: 'push',
        mechanic: 'compound',
        name: 'Parallel Bar Dip',
        primaryMuscle: 'triceps',
        secondaryMuscles: ['chest', 'shoulders'],
        slug: 'parallel-bar-dip',
    },
    {
        aliases: ['close grip bench'],
        defaultRestSeconds: 150,
        equipment: 'barbell',
        force: 'push',
        mechanic: 'compound',
        name: 'Close-Grip Bench Press',
        primaryMuscle: 'triceps',
        secondaryMuscles: ['chest', 'shoulders'],
        slug: 'close-grip-bench-press',
    },
    {
        aliases: ['plank'],
        defaultRestSeconds: 60,
        equipment: 'bodyweight',
        force: 'static',
        mechanic: 'isolation',
        name: 'Plank',
        primaryMuscle: 'abs',
        secondaryMuscles: ['shoulders'],
        slug: 'plank',
    },
    {
        aliases: ['hanging leg raise'],
        defaultRestSeconds: 60,
        equipment: 'bodyweight',
        force: 'pull',
        mechanic: 'isolation',
        name: 'Hanging Leg Raise',
        primaryMuscle: 'abs',
        secondaryMuscles: ['forearms'],
        slug: 'hanging-leg-raise',
    },
    {
        aliases: ['cable crunch'],
        defaultRestSeconds: 60,
        equipment: 'cable',
        force: 'pull',
        mechanic: 'isolation',
        name: 'Cable Crunch',
        primaryMuscle: 'abs',
        secondaryMuscles: [],
        slug: 'cable-crunch',
    },
    {
        aliases: ['ab wheel'],
        defaultRestSeconds: 60,
        equipment: 'other',
        force: 'pull',
        mechanic: 'isolation',
        name: 'Ab Wheel Rollout',
        primaryMuscle: 'abs',
        secondaryMuscles: ['shoulders'],
        slug: 'ab-wheel-rollout',
    },
    {
        aliases: ['wrist curl'],
        defaultRestSeconds: 45,
        equipment: 'dumbbell',
        force: 'pull',
        mechanic: 'isolation',
        name: 'Wrist Curl',
        primaryMuscle: 'forearms',
        secondaryMuscles: [],
        slug: 'wrist-curl',
    },
    {
        aliases: ['farmer carry', 'farmer walk'],
        defaultRestSeconds: 90,
        equipment: 'dumbbell',
        force: 'carry',
        mechanic: 'compound',
        name: "Farmer's Carry",
        primaryMuscle: 'traps',
        secondaryMuscles: ['forearms', 'abs', 'back'],
        slug: 'farmers-carry',
    },
    {
        aliases: ['kb swing'],
        defaultRestSeconds: 90,
        equipment: 'kettlebell',
        force: 'hinge',
        mechanic: 'compound',
        name: 'Kettlebell Swing',
        primaryMuscle: 'glutes',
        secondaryMuscles: ['hamstrings', 'back', 'shoulders'],
        slug: 'kettlebell-swing',
    },
    {
        aliases: ['rower', 'erg'],
        defaultRestSeconds: 60,
        equipment: 'cardio',
        force: 'pull',
        mechanic: 'compound',
        name: 'Rowing Machine',
        primaryMuscle: 'back',
        secondaryMuscles: ['lats', 'quads', 'hamstrings'],
        slug: 'rowing-machine',
    },
    {
        aliases: ['treadmill'],
        defaultRestSeconds: 0,
        equipment: 'cardio',
        force: 'push',
        mechanic: 'compound',
        name: 'Treadmill Run',
        primaryMuscle: 'quads',
        secondaryMuscles: ['hamstrings', 'glutes', 'calves'],
        slug: 'treadmill-run',
    },
];

export class SeedLiftingExercises extends DatabaseSeeder {
    readonly name = 'lifting:exercises';
    override readonly priority = 10;

    async run(): Promise<void> {
        for (const ex of EXERCISES) {
            const [row] = await db
                .insert(liftingExercise)
                .values({
                    defaultRestSeconds: ex.defaultRestSeconds ?? null,
                    equipment: ex.equipment,
                    force: ex.force,
                    isCustom: false,
                    mechanic: ex.mechanic,
                    name: ex.name,
                    ownerId: null,
                    primaryMuscle: ex.primaryMuscle,
                    secondaryMuscles: ex.secondaryMuscles,
                    slug: ex.slug,
                    tags: ex.tags ?? [],
                })
                .onConflictDoNothing()
                .returning({ id: liftingExercise.id });

            if (row && ex.aliases.length > 0) {
                await db
                    .insert(liftingExerciseAlias)
                    .values(
                        ex.aliases.map((alias) => ({
                            alias,
                            exerciseId: row.id,
                        })),
                    )
                    .onConflictDoNothing();
            }
        }
    }
}
