export enum AlertKind {
    CalendarInactivity = 'calendar-inactivity',
    ConductPattern = 'conduct-pattern',
    ConsistencyNearBreach = 'consistency-near-breach',
    CooldownActive = 'cooldown-active',
    DashboardFloorMismatch = 'dashboard-floor-mismatch',
    EvalDayCapNear = 'eval-day-cap-near',
    IdleSessionLimit = 'idle-session-limit',
    InvalidStoredDate = 'invalid-stored-date',
    LifetimeDollarCapNear = 'lifetime-dollar-cap-near',
    LifetimePayoutCountNear = 'lifetime-payout-count-near',
    LiveExclusivity = 'live-exclusivity',
    LiveTriggerNear = 'live-trigger-near',
    MixedStageCopyGroup = 'mixed-stage-copy-group',
    NearFloor = 'near-floor',
    PayoutCountMismatch = 'payout-count-mismatch',
    PayoutDollarMismatch = 'payout-dollar-mismatch',
    PayoutEligible = 'payout-eligible',
    PayoutReadyWithdrawableDrop = 'payout-ready-withdrawable-drop',
    PlanRulesChanged = 'plan-rules-changed',
    PooledCapReached = 'pooled-cap-reached',
    StaleSnapshot = 'stale-snapshot',
    SubscriptionRenewalDue = 'subscription-renewal-due',
    TierChange = 'tier-change',
    UnresolvablePlan = 'unresolvable-plan',
    WeeklyReviewDue = 'weekly-review-due',
}

const ALERT_KIND_LABELS: Readonly<Record<AlertKind, string>> = {
    [AlertKind.CalendarInactivity]: 'Calendar inactivity',
    [AlertKind.ConductPattern]: 'Conduct pattern',
    [AlertKind.ConsistencyNearBreach]: 'Consistency near breach',
    [AlertKind.CooldownActive]: 'Cooldown active',
    [AlertKind.DashboardFloorMismatch]: 'Dashboard floor mismatch',
    [AlertKind.EvalDayCapNear]: 'Eval day cap',
    [AlertKind.IdleSessionLimit]: 'Idle session limit',
    [AlertKind.InvalidStoredDate]: 'Invalid stored date',
    [AlertKind.LifetimeDollarCapNear]: 'Lifetime payout dollar cap',
    [AlertKind.LifetimePayoutCountNear]: 'Lifetime payout count',
    [AlertKind.LiveExclusivity]: 'Live exclusivity',
    [AlertKind.LiveTriggerNear]: 'Live trigger near',
    [AlertKind.MixedStageCopyGroup]: 'Mixed-stage copy group',
    [AlertKind.NearFloor]: 'Near the floor',
    [AlertKind.PayoutCountMismatch]: 'Payout count mismatch',
    [AlertKind.PayoutDollarMismatch]: 'Payout dollar mismatch',
    [AlertKind.PayoutEligible]: 'Payout eligible',
    [AlertKind.PayoutReadyWithdrawableDrop]: 'Payout-ready withdrawable drop',
    [AlertKind.PlanRulesChanged]: 'Plan rules changed',
    [AlertKind.PooledCapReached]: 'Pooled account cap reached',
    [AlertKind.StaleSnapshot]: 'Stale snapshot',
    [AlertKind.SubscriptionRenewalDue]: 'Subscription renewal due',
    [AlertKind.TierChange]: 'DLL or contract tier change',
    [AlertKind.UnresolvablePlan]: 'Unresolvable plan',
    [AlertKind.WeeklyReviewDue]: 'Weekly review due',
};

export function alertKindLabel(kind: AlertKind): string {
    return ALERT_KIND_LABELS[kind];
}
