export enum AlertKind {
    BankrollLossRiskAboveThreshold = 'bankroll-loss-risk-above-threshold',
    CalendarInactivity = 'calendar-inactivity',
    CapacityExceeded = 'capacity-exceeded',
    ConcentratedFirmProfit = 'concentrated-firm-profit',
    ConductPattern = 'conduct-pattern',
    ConsistencyNearBreach = 'consistency-near-breach',
    CooldownActive = 'cooldown-active',
    DashboardFloorMismatch = 'dashboard-floor-mismatch',
    EvalDayCapNear = 'eval-day-cap-near',
    FirmPayoutTotalMismatch = 'firm-payout-total-mismatch',
    IdleSessionLimit = 'idle-session-limit',
    InvalidStoredDate = 'invalid-stored-date',
    LargeDayLoss = 'large-day-loss',
    LifetimeDollarCapNear = 'lifetime-dollar-cap-near',
    LifetimePayoutCountNear = 'lifetime-payout-count-near',
    LiveExclusivity = 'live-exclusivity',
    LiveTriggerNear = 'live-trigger-near',
    MixedStageCopyGroup = 'mixed-stage-copy-group',
    NearFloor = 'near-floor',
    PayoutCountMismatch = 'payout-count-mismatch',
    PayoutDollarMismatch = 'payout-dollar-mismatch',
    PayoutEligible = 'payout-eligible',
    PayoutReadyOpenRisk = 'payout-ready-open-risk',
    PayoutReadyWithdrawableDrop = 'payout-ready-withdrawable-drop',
    PlanRulesChanged = 'plan-rules-changed',
    PooledCapReached = 'pooled-cap-reached',
    RoundBudgetReached = 'round-budget-reached',
    StaleSnapshot = 'stale-snapshot',
    SubscriptionRenewalDue = 'subscription-renewal-due',
    TierChange = 'tier-change',
    UnresolvablePlan = 'unresolvable-plan',
    WeeklyReviewDue = 'weekly-review-due',
}

const ALERT_KIND_LABELS: Readonly<Record<AlertKind, string>> = {
    [AlertKind.BankrollLossRiskAboveThreshold]:
        'Bankroll loss risk above threshold',
    [AlertKind.CalendarInactivity]: 'Calendar inactivity',
    [AlertKind.CapacityExceeded]: 'Daily account capacity exceeded',
    [AlertKind.ConcentratedFirmProfit]: 'Profit concentrated at one firm',
    [AlertKind.ConductPattern]: 'Conduct pattern',
    [AlertKind.ConsistencyNearBreach]: 'Consistency near breach',
    [AlertKind.CooldownActive]: 'Cooldown active',
    [AlertKind.DashboardFloorMismatch]: 'Dashboard floor mismatch',
    [AlertKind.EvalDayCapNear]: 'Eval day cap',
    [AlertKind.FirmPayoutTotalMismatch]: 'Firm payout total mismatch',
    [AlertKind.IdleSessionLimit]: 'Idle session limit',
    [AlertKind.InvalidStoredDate]: 'Invalid stored date',
    [AlertKind.LargeDayLoss]: 'Large day loss',
    [AlertKind.LifetimeDollarCapNear]: 'Lifetime payout dollar cap',
    [AlertKind.LifetimePayoutCountNear]: 'Lifetime payout count',
    [AlertKind.LiveExclusivity]: 'Live exclusivity',
    [AlertKind.LiveTriggerNear]: 'Live trigger near',
    [AlertKind.MixedStageCopyGroup]: 'Mixed-stage copy group',
    [AlertKind.NearFloor]: 'Near the floor',
    [AlertKind.PayoutCountMismatch]: 'Payout count mismatch',
    [AlertKind.PayoutDollarMismatch]: 'Payout dollar mismatch',
    [AlertKind.PayoutEligible]: 'Payout eligible',
    [AlertKind.PayoutReadyOpenRisk]:
        'Payout-ready account risked above the documented rung',
    [AlertKind.PayoutReadyWithdrawableDrop]: 'Payout-ready withdrawable drop',
    [AlertKind.PlanRulesChanged]: 'Plan rules changed',
    [AlertKind.PooledCapReached]: 'Pooled account cap reached',
    [AlertKind.RoundBudgetReached]: 'Round budget reached',
    [AlertKind.StaleSnapshot]: 'Stale snapshot',
    [AlertKind.SubscriptionRenewalDue]: 'Subscription renewal due',
    [AlertKind.TierChange]: 'DLL or contract tier change',
    [AlertKind.UnresolvablePlan]: 'Unresolvable plan',
    [AlertKind.WeeklyReviewDue]: 'Weekly review due',
};

export function alertKindLabel(kind: AlertKind): string {
    return ALERT_KIND_LABELS[kind];
}
