export const DEFAULT_ACTION_STEP_MULTIPLE = 0.05;
export const DEFAULT_MAX_ACTION_MULTIPLE = 1;
export const DEFAULT_CUSHION_STEP_MULTIPLE = 0.1;
export const DEFAULT_MAX_CUSHION_MULTIPLE = 6;
export const DEFAULT_TAIL_CUSHION_STEP_MULTIPLE = 1;
export const DEFAULT_MAX_TAIL_CUSHION_MULTIPLE = 30;
