export enum AssumptionKind {
    CalendarAnchorMissing = 'calendar-anchor-missing',
    ContractCapInstrumentAssumed = 'contract-cap-instrument-assumed',
    CumulativeQualifyingDaysAssumed = 'cumulative-qualifying-days-assumed',
    CycleBestDayProfitAssumedWorstCase = 'cycle-best-day-profit-assumed-worst-case',
    DashboardFloorMismatch = 'dashboard-floor-mismatch',
    ElapsedDaysApproximatedFromTradingDays = 'elapsed-days-approximated-from-trading-days',
    FundedResetsFromEvents = 'funded-resets-from-events',
    GrossOnlyPayouts = 'gross-only-payouts',
    LastPayoutBalanceAssumedCurrent = 'last-payout-balance-assumed-current',
    LiveModelApproximation = 'live-model-approximation',
    LiveNotModeled = 'live-not-modeled',
    LiveTriggersNotChecked = 'live-triggers-not-checked',
    NoHolidayCalendar = 'no-holiday-calendar',
    PeakOrderAssumed = 'peak-order-assumed',
    PendingPayoutDeducted = 'pending-payout-deducted',
    PercentCandidatesLeftOut = 'percent-candidates-left-out',
    PositionSizingUnspecified = 'position-sizing-unspecified',
    RebuyLagAssumed = 'rebuy-lag-assumed',
    SizingRule = 'sizing-rule',
    TopStepLfaProgressDefaulted = 'topstep-lfa-progress-defaulted',
    TopStepLiveReserveDefaulted = 'topstep-live-reserve-defaulted',
}
