export enum AssumptionKind {
    CalendarAnchorMissing = 'calendar-anchor-missing',
    ContractCapInstrumentAssumed = 'contract-cap-instrument-assumed',
    CumulativeQualifyingDaysAssumed = 'cumulative-qualifying-days-assumed',
    DashboardFloorMismatch = 'dashboard-floor-mismatch',
    FundedResetsFromEvents = 'funded-resets-from-events',
    GrossOnlyPayouts = 'gross-only-payouts',
    LiveModelApproximation = 'live-model-approximation',
    LiveNotModeled = 'live-not-modeled',
    LiveTriggersNotChecked = 'live-triggers-not-checked',
    NoHolidayCalendar = 'no-holiday-calendar',
    PeakOrderAssumed = 'peak-order-assumed',
    PendingPayoutDeducted = 'pending-payout-deducted',
    RebuyLagAssumed = 'rebuy-lag-assumed',
    SizingRule = 'sizing-rule',
    TopStepLfaProgressDefaulted = 'topstep-lfa-progress-defaulted',
    TopStepLiveReserveDefaulted = 'topstep-live-reserve-defaulted',
}
