export enum SnapshotInputField {
    AsOf = 'asOf',
    Balance = 'balance',
    BalanceAtLastPayout = 'balanceAtLastPayout',
    CumulativePayout = 'cumulativePayout',
    CycleBestDayProfit = 'cycleBestDayProfit',
    DashboardConvention = 'dashboardConvention',
    DashboardFloor = 'dashboardFloor',
    EvalBestDayProfit = 'evalBestDayProfit',
    FirstFundedTradeOn = 'firstFundedTradeOn',
    FloorAtLastPayout = 'floorAtLastPayout',
    FundedOn = 'fundedOn',
    FundedResetsUsed = 'fundedResetsUsed',
    HighestEodBalance = 'highestEodBalance',
    HighestIntradayBalance = 'highestIntradayBalance',
    LastPayoutOn = 'lastPayoutOn',
    LastTradedOn = 'lastTradedOn',
    LiveStartBalance = 'liveStartBalance',
    PayoutsTaken = 'payoutsTaken',
    PendingPayouts = 'pendingPayouts',
    PurchasedOn = 'purchasedOn',
    QualifyingDaysSinceLastPayout = 'qualifyingDaysSinceLastPayout',
    Stage = 'stage',
    TradingDays = 'tradingDays',
}
